{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 7,
      "metadata": {
        "id": "g_bAmQczaCHR"
      },
      "outputs": [],
      "source": [
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "\n",
        "from sklearn.model_selection import train_test_split\n",
        "from sklearn.preprocessing import StandardScaler, OneHotEncoder\n",
        "from sklearn.compose import ColumnTransformer\n",
        "from sklearn.pipeline import Pipeline\n",
        "from sklearn.linear_model import LogisticRegression\n",
        "\n",
        "from sklearn.metrics import (\n",
        "    accuracy_score,\n",
        "    classification_report,\n",
        "    confusion_matrix\n",
        ")"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from google.colab import files\n",
        "\n",
        "uploaded = files.upload()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 128
        },
        "id": "rimgF9EBbNbC",
        "outputId": "743466f2-04a1-4ede-c9c0-69efcad8f957"
      },
      "execution_count": 11,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ],
            "text/html": [
              "\n",
              "     <input type=\"file\" id=\"files-20dd3a48-4de8-46fd-8fcf-6518b270a990\" name=\"files[]\" multiple disabled\n",
              "        style=\"border:none\" />\n",
              "     <output id=\"result-20dd3a48-4de8-46fd-8fcf-6518b270a990\">\n",
              "      Upload widget is only available when the cell has been executed in the\n",
              "      current browser session. Please rerun this cell to enable.\n",
              "      </output>\n",
              "      <script>// Copyright 2017 Google LLC\n",
              "//\n",
              "// Licensed under the Apache License, Version 2.0 (the \"License\");\n",
              "// you may not use this file except in compliance with the License.\n",
              "// You may obtain a copy of the License at\n",
              "//\n",
              "//      http://www.apache.org/licenses/LICENSE-2.0\n",
              "//\n",
              "// Unless required by applicable law or agreed to in writing, software\n",
              "// distributed under the License is distributed on an \"AS IS\" BASIS,\n",
              "// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n",
              "// See the License for the specific language governing permissions and\n",
              "// limitations under the License.\n",
              "\n",
              "/**\n",
              " * @fileoverview Helpers for google.colab Python module.\n",
              " */\n",
              "(function(scope) {\n",
              "function span(text, styleAttributes = {}) {\n",
              "  const element = document.createElement('span');\n",
              "  element.textContent = text;\n",
              "  for (const key of Object.keys(styleAttributes)) {\n",
              "    element.style[key] = styleAttributes[key];\n",
              "  }\n",
              "  return element;\n",
              "}\n",
              "\n",
              "// Max number of bytes which will be uploaded at a time.\n",
              "const MAX_PAYLOAD_SIZE = 100 * 1024;\n",
              "\n",
              "function _uploadFiles(inputId, outputId) {\n",
              "  const steps = uploadFilesStep(inputId, outputId);\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  // Cache steps on the outputElement to make it available for the next call\n",
              "  // to uploadFilesContinue from Python.\n",
              "  outputElement.steps = steps;\n",
              "\n",
              "  return _uploadFilesContinue(outputId);\n",
              "}\n",
              "\n",
              "// This is roughly an async generator (not supported in the browser yet),\n",
              "// where there are multiple asynchronous steps and the Python side is going\n",
              "// to poll for completion of each step.\n",
              "// This uses a Promise to block the python side on completion of each step,\n",
              "// then passes the result of the previous step as the input to the next step.\n",
              "function _uploadFilesContinue(outputId) {\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  const steps = outputElement.steps;\n",
              "\n",
              "  const next = steps.next(outputElement.lastPromiseValue);\n",
              "  return Promise.resolve(next.value.promise).then((value) => {\n",
              "    // Cache the last promise value to make it available to the next\n",
              "    // step of the generator.\n",
              "    outputElement.lastPromiseValue = value;\n",
              "    return next.value.response;\n",
              "  });\n",
              "}\n",
              "\n",
              "/**\n",
              " * Generator function which is called between each async step of the upload\n",
              " * process.\n",
              " * @param {string} inputId Element ID of the input file picker element.\n",
              " * @param {string} outputId Element ID of the output display.\n",
              " * @return {!Iterable<!Object>} Iterable of next steps.\n",
              " */\n",
              "function* uploadFilesStep(inputId, outputId) {\n",
              "  const inputElement = document.getElementById(inputId);\n",
              "  inputElement.disabled = false;\n",
              "\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  outputElement.innerHTML = '';\n",
              "\n",
              "  const pickedPromise = new Promise((resolve) => {\n",
              "    inputElement.addEventListener('change', (e) => {\n",
              "      resolve(e.target.files);\n",
              "    });\n",
              "  });\n",
              "\n",
              "  const cancel = document.createElement('button');\n",
              "  inputElement.parentElement.appendChild(cancel);\n",
              "  cancel.textContent = 'Cancel upload';\n",
              "  const cancelPromise = new Promise((resolve) => {\n",
              "    cancel.onclick = () => {\n",
              "      resolve(null);\n",
              "    };\n",
              "  });\n",
              "\n",
              "  // Wait for the user to pick the files.\n",
              "  const files = yield {\n",
              "    promise: Promise.race([pickedPromise, cancelPromise]),\n",
              "    response: {\n",
              "      action: 'starting',\n",
              "    }\n",
              "  };\n",
              "\n",
              "  cancel.remove();\n",
              "\n",
              "  // Disable the input element since further picks are not allowed.\n",
              "  inputElement.disabled = true;\n",
              "\n",
              "  if (!files) {\n",
              "    return {\n",
              "      response: {\n",
              "        action: 'complete',\n",
              "      }\n",
              "    };\n",
              "  }\n",
              "\n",
              "  for (const file of files) {\n",
              "    const li = document.createElement('li');\n",
              "    li.append(span(file.name, {fontWeight: 'bold'}));\n",
              "    li.append(span(\n",
              "        `(${file.type || 'n/a'}) - ${file.size} bytes, ` +\n",
              "        `last modified: ${\n",
              "            file.lastModifiedDate ? file.lastModifiedDate.toLocaleDateString() :\n",
              "                                    'n/a'} - `));\n",
              "    const percent = span('0% done');\n",
              "    li.appendChild(percent);\n",
              "\n",
              "    outputElement.appendChild(li);\n",
              "\n",
              "    const fileDataPromise = new Promise((resolve) => {\n",
              "      const reader = new FileReader();\n",
              "      reader.onload = (e) => {\n",
              "        resolve(e.target.result);\n",
              "      };\n",
              "      reader.readAsArrayBuffer(file);\n",
              "    });\n",
              "    // Wait for the data to be ready.\n",
              "    let fileData = yield {\n",
              "      promise: fileDataPromise,\n",
              "      response: {\n",
              "        action: 'continue',\n",
              "      }\n",
              "    };\n",
              "\n",
              "    // Use a chunked sending to avoid message size limits. See b/62115660.\n",
              "    let position = 0;\n",
              "    do {\n",
              "      const length = Math.min(fileData.byteLength - position, MAX_PAYLOAD_SIZE);\n",
              "      const chunk = new Uint8Array(fileData, position, length);\n",
              "      position += length;\n",
              "\n",
              "      const base64 = btoa(String.fromCharCode.apply(null, chunk));\n",
              "      yield {\n",
              "        response: {\n",
              "          action: 'append',\n",
              "          file: file.name,\n",
              "          data: base64,\n",
              "        },\n",
              "      };\n",
              "\n",
              "      let percentDone = fileData.byteLength === 0 ?\n",
              "          100 :\n",
              "          Math.round((position / fileData.byteLength) * 100);\n",
              "      percent.textContent = `${percentDone}% done`;\n",
              "\n",
              "    } while (position < fileData.byteLength);\n",
              "  }\n",
              "\n",
              "  // All done.\n",
              "  yield {\n",
              "    response: {\n",
              "      action: 'complete',\n",
              "    }\n",
              "  };\n",
              "}\n",
              "\n",
              "scope.google = scope.google || {};\n",
              "scope.google.colab = scope.google.colab || {};\n",
              "scope.google.colab._files = {\n",
              "  _uploadFiles,\n",
              "  _uploadFilesContinue,\n",
              "};\n",
              "})(self);\n",
              "</script> "
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Saving diet_recommendations_dataset.csv to diet_recommendations_dataset (2).csv\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# ============================================================\n",
        "# DIABETES SEVERITY — MULTINOMIAL LOGISTIC REGRESSION\n",
        "# ============================================================\n",
        "\n",
        "# 1. Import libraries\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "\n",
        "from sklearn.model_selection import train_test_split\n",
        "from sklearn.preprocessing import StandardScaler, OneHotEncoder\n",
        "from sklearn.compose import ColumnTransformer\n",
        "from sklearn.pipeline import Pipeline\n",
        "from sklearn.linear_model import LogisticRegression\n",
        "from sklearn.metrics import (\n",
        "    accuracy_score,\n",
        "    classification_report,\n",
        "    confusion_matrix\n",
        ")\n",
        "\n",
        "# ============================================================\n",
        "# 2. Load dataset\n",
        "# ============================================================\n",
        "\n",
        "df = pd.read_csv(\"diet_recommendations_dataset.csv\")\n",
        "\n",
        "print(\"=\" * 60)\n",
        "print(\"DATASET INFORMATION\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "print(\"Shape:\", df.shape)\n",
        "print(\"\\nColumns:\")\n",
        "print(df.columns.tolist())\n",
        "\n",
        "print(\"\\nFirst 5 rows:\")\n",
        "display(df.head())\n",
        "\n",
        "# ============================================================\n",
        "# 3. Basic data checking\n",
        "# ============================================================\n",
        "\n",
        "print(\"\\n\" + \"=\" * 60)\n",
        "print(\"MISSING VALUES\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "print(df.isnull().sum())\n",
        "\n",
        "print(\"\\nTotal missing values:\", df.isnull().sum().sum())\n",
        "\n",
        "print(\"\\nDuplicate rows:\", df.duplicated().sum())\n",
        "\n",
        "# Remove duplicates\n",
        "df = df.drop_duplicates()\n",
        "\n",
        "# ============================================================\n",
        "# 4. Target variable — Severity\n",
        "# ============================================================\n",
        "\n",
        "print(\"\\n\" + \"=\" * 60)\n",
        "print(\"DIABETES SEVERITY\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "print(df[\"Severity\"].value_counts())\n",
        "\n",
        "# Plot target distribution\n",
        "plt.figure(figsize=(7, 5))\n",
        "sns.countplot(data=df, x=\"Severity\")\n",
        "plt.title(\"Diabetes Severity Distribution\")\n",
        "plt.xlabel(\"Severity\")\n",
        "plt.ylabel(\"Number of Patients\")\n",
        "plt.show()\n",
        "\n",
        "# ============================================================\n",
        "# 5. Basic EDA\n",
        "# ============================================================\n",
        "\n",
        "print(\"\\n\" + \"=\" * 60)\n",
        "print(\"STATISTICAL SUMMARY\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "display(df.describe())\n",
        "\n",
        "# BMI vs Severity\n",
        "if \"BMI\" in df.columns:\n",
        "    plt.figure(figsize=(7, 5))\n",
        "    sns.boxplot(data=df, x=\"Severity\", y=\"BMI\")\n",
        "    plt.title(\"BMI by Diabetes Severity\")\n",
        "    plt.show()\n",
        "\n",
        "# Glucose vs Severity\n",
        "if \"Glucose_mg/dL\" in df.columns:\n",
        "    plt.figure(figsize=(7, 5))\n",
        "    sns.boxplot(data=df, x=\"Severity\", y=\"Glucose_mg/dL\")\n",
        "    plt.title(\"Glucose Level by Diabetes Severity\")\n",
        "    plt.show()\n",
        "\n",
        "# ============================================================\n",
        "# 6. Separate features and target\n",
        "# ============================================================\n",
        "\n",
        "X = df.drop(\"Severity\", axis=1)\n",
        "y = df[\"Severity\"]\n",
        "\n",
        "# Remove ID column if present\n",
        "if \"Patient_ID\" in X.columns:\n",
        "    X = X.drop(\"Patient_ID\", axis=1)\n",
        "\n",
        "# Remove recommendation column\n",
        "if \"Diet_Recommendation\" in X.columns:\n",
        "    X = X.drop(\"Diet_Recommendation\", axis=1)\n",
        "\n",
        "print(\"\\nFeatures:\")\n",
        "print(X.columns.tolist())\n",
        "\n",
        "print(\"\\nTarget:\")\n",
        "print(y.name)\n",
        "\n",
        "# ============================================================\n",
        "# 7. Identify numerical and categorical features\n",
        "# ============================================================\n",
        "\n",
        "numeric_features = X.select_dtypes(\n",
        "    include=[\"int64\", \"float64\"]\n",
        ").columns.tolist()\n",
        "\n",
        "categorical_features = X.select_dtypes(\n",
        "    include=[\"object\", \"category\"]\n",
        ").columns.tolist()\n",
        "\n",
        "print(\"\\nNumerical features:\")\n",
        "print(numeric_features)\n",
        "\n",
        "print(\"\\nCategorical features:\")\n",
        "print(categorical_features)\n",
        "\n",
        "# ============================================================\n",
        "# 8. Train/Test split\n",
        "# ============================================================\n",
        "\n",
        "X_train, X_test, y_train, y_test = train_test_split(\n",
        "    X,\n",
        "    y,\n",
        "    test_size=0.20,\n",
        "    random_state=42,\n",
        "    stratify=y\n",
        ")\n",
        "\n",
        "print(\"\\nTraining samples:\", len(X_train))\n",
        "print(\"Testing samples:\", len(X_test))\n",
        "\n",
        "# ============================================================\n",
        "# 9. Preprocessing\n",
        "# ============================================================\n",
        "\n",
        "preprocessor = ColumnTransformer(\n",
        "    transformers=[\n",
        "        (\n",
        "            \"num\",\n",
        "            StandardScaler(),\n",
        "            numeric_features\n",
        "        ),\n",
        "        (\n",
        "            \"cat\",\n",
        "            OneHotEncoder(handle_unknown=\"ignore\"),\n",
        "            categorical_features\n",
        "        )\n",
        "    ]\n",
        ")\n",
        "\n",
        "# ============================================================\n",
        "# 10. Multinomial Logistic Regression\n",
        "# ============================================================\n",
        "\n",
        "model = LogisticRegression(\n",
        "    max_iter=1000,\n",
        "    multi_class=\"multinomial\",\n",
        "    random_state=42\n",
        ")\n",
        "\n",
        "# Complete pipeline\n",
        "pipeline = Pipeline(\n",
        "    steps=[\n",
        "        (\"preprocessing\", preprocessor),\n",
        "        (\"model\", model)\n",
        "    ]\n",
        ")\n",
        "\n",
        "# ============================================================\n",
        "# 11. Train model\n",
        "# ============================================================\n",
        "\n",
        "pipeline.fit(X_train, y_train)\n",
        "\n",
        "print(\"\\n\" + \"=\" * 60)\n",
        "print(\"MODEL TRAINED SUCCESSFULLY\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "# ============================================================\n",
        "# 12. Predictions\n",
        "# ============================================================\n",
        "\n",
        "y_pred = pipeline.predict(X_test)\n",
        "\n",
        "# ============================================================\n",
        "# 13. Accuracy\n",
        "# ============================================================\n",
        "\n",
        "accuracy = accuracy_score(y_test, y_pred)\n",
        "\n",
        "print(\"\\n\" + \"=\" * 60)\n",
        "print(\"MODEL ACCURACY\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "print(f\"Accuracy: {accuracy:.4f}\")\n",
        "print(f\"Accuracy: {accuracy * 100:.2f}%\")\n",
        "\n",
        "# ============================================================\n",
        "# 14. Classification Report\n",
        "# ============================================================\n",
        "\n",
        "print(\"\\n\" + \"=\" * 60)\n",
        "print(\"CLASSIFICATION REPORT\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "print(classification_report(y_test, y_pred))\n",
        "\n",
        "# ============================================================\n",
        "# 15. Confusion Matrix\n",
        "# ============================================================\n",
        "\n",
        "cm = confusion_matrix(y_test, y_pred)\n",
        "\n",
        "plt.figure(figsize=(7, 5))\n",
        "\n",
        "sns.heatmap(\n",
        "    cm,\n",
        "    annot=True,\n",
        "    fmt=\"d\",\n",
        "    cmap=\"Blues\",\n",
        "    xticklabels=pipeline.classes_,\n",
        "    yticklabels=pipeline.classes_\n",
        ")\n",
        "\n",
        "plt.xlabel(\"Predicted Severity\")\n",
        "plt.ylabel(\"Actual Severity\")\n",
        "plt.title(\"Confusion Matrix\")\n",
        "\n",
        "plt.show()\n",
        "\n",
        "# ============================================================\n",
        "# 16. Probability-based predictions\n",
        "# ============================================================\n",
        "\n",
        "probabilities = pipeline.predict_proba(X_test)\n",
        "\n",
        "print(\"\\n\" + \"=\" * 60)\n",
        "print(\"CLASS PROBABILITIES — FIRST 5 PATIENTS\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "print(\"Classes:\", pipeline.classes_)\n",
        "print()\n",
        "\n",
        "for i in range(min(5, len(X_test))):\n",
        "    print(f\"Patient {i+1}\")\n",
        "    print(\"Actual:\", y_test.iloc[i])\n",
        "    print(\"Predicted:\", y_pred[i])\n",
        "\n",
        "    for class_name, probability in zip(\n",
        "        pipeline.classes_,\n",
        "        probabilities[i]\n",
        "    ):\n",
        "        print(f\"{class_name}: {probability:.2%}\")\n",
        "\n",
        "    print(\"-\" * 40)\n",
        "\n",
        "# ============================================================\n",
        "# 17. Create prediction results table\n",
        "# ============================================================\n",
        "\n",
        "results = pd.DataFrame({\n",
        "    \"Actual\": y_test.values,\n",
        "    \"Predicted\": y_pred\n",
        "})\n",
        "\n",
        "for i, class_name in enumerate(pipeline.classes_):\n",
        "    results[f\"Probability_{class_name}\"] = probabilities[:, i]\n",
        "\n",
        "print(\"\\n\" + \"=\" * 60)\n",
        "print(\"PREDICTION RESULTS\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "display(results.head(10))\n",
        "\n",
        "# ============================================================\n",
        "# 18. Final summary\n",
        "# ============================================================\n",
        "\n",
        "print(\"\\n\" + \"=\" * 60)\n",
        "print(\"PROJECT SUMMARY\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "print(\"\"\"\n",
        "Skill Program:\n",
        "Diabetes Severity — Multinomial Logistic Regression\n",
        "\n",
        "Skills demonstrated:\n",
        "✓ Multiclass Classification\n",
        "✓ Multinomial Logistic Regression\n",
        "✓ Numerical Feature Scaling\n",
        "✓ Categorical Feature Encoding\n",
        "✓ Machine Learning Pipeline\n",
        "✓ Probability-Based Predictions\n",
        "✓ Accuracy\n",
        "✓ Precision\n",
        "✓ Recall\n",
        "✓ F1-Score\n",
        "✓ Confusion Matrix\n",
        "\"\"\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "id": "utbBTPR7cD6a",
        "outputId": "9186ba61-b15e-49ba-b1f1-5e2cefa27671"
      },
      "execution_count": 24,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "============================================================\n",
            "DATASET INFORMATION\n",
            "============================================================\n",
            "Shape: (1000, 20)\n",
            "\n",
            "Columns:\n",
            "['Patient_ID', 'Age', 'Gender', 'Weight_kg', 'Height_cm', 'BMI', 'Disease_Type', 'Severity', 'Physical_Activity_Level', 'Daily_Caloric_Intake', 'Cholesterol_mg/dL', 'Blood_Pressure_mmHg', 'Glucose_mg/dL', 'Dietary_Restrictions', 'Allergies', 'Preferred_Cuisine', 'Weekly_Exercise_Hours', 'Adherence_to_Diet_Plan', 'Dietary_Nutrient_Imbalance_Score', 'Diet_Recommendation']\n",
            "\n",
            "First 5 rows:\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "  Patient_ID  Age  Gender  Weight_kg  Height_cm   BMI  Disease_Type  Severity  \\\n",
              "0      P0001   56    Male       58.4        160  22.8       Obesity  Moderate   \n",
              "1      P0002   69    Male      101.2        169  35.4      Diabetes      Mild   \n",
              "2      P0003   46  Female       63.5        173  21.2  Hypertension      Mild   \n",
              "3      P0004   32    Male       58.1        164  21.6           NaN      Mild   \n",
              "4      P0005   60    Male       79.5        197  20.5      Diabetes  Moderate   \n",
              "\n",
              "  Physical_Activity_Level  Daily_Caloric_Intake  Cholesterol_mg/dL  \\\n",
              "0                Moderate                  3079              173.3   \n",
              "1                Moderate                  3032              199.2   \n",
              "2               Sedentary                  1737              181.0   \n",
              "3                Moderate                  2657              168.2   \n",
              "4               Sedentary                  3496              200.4   \n",
              "\n",
              "   Blood_Pressure_mmHg  Glucose_mg/dL Dietary_Restrictions Allergies  \\\n",
              "0                  133          116.3                  NaN   Peanuts   \n",
              "1                  120          137.1                  NaN   Peanuts   \n",
              "2                  121          109.6                  NaN   Peanuts   \n",
              "3                  144          159.4                  NaN       NaN   \n",
              "4                  172          182.3            Low_Sugar       NaN   \n",
              "\n",
              "  Preferred_Cuisine  Weekly_Exercise_Hours  Adherence_to_Diet_Plan  \\\n",
              "0           Mexican                    3.1                    96.6   \n",
              "1           Chinese                    4.5                    63.2   \n",
              "2           Chinese                    3.8                    57.5   \n",
              "3           Mexican                    4.3                    54.5   \n",
              "4           Italian                    9.8                    78.2   \n",
              "\n",
              "   Dietary_Nutrient_Imbalance_Score Diet_Recommendation  \n",
              "0                               3.1            Balanced  \n",
              "1                               0.6            Low_Carb  \n",
              "2                               4.6          Low_Sodium  \n",
              "3                               0.4            Balanced  \n",
              "4                               4.7            Low_Carb  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-f8d0c255-9adf-45c9-9b2f-e938ce417c52\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>Patient_ID</th>\n",
              "      <th>Age</th>\n",
              "      <th>Gender</th>\n",
              "      <th>Weight_kg</th>\n",
              "      <th>Height_cm</th>\n",
              "      <th>BMI</th>\n",
              "      <th>Disease_Type</th>\n",
              "      <th>Severity</th>\n",
              "      <th>Physical_Activity_Level</th>\n",
              "      <th>Daily_Caloric_Intake</th>\n",
              "      <th>Cholesterol_mg/dL</th>\n",
              "      <th>Blood_Pressure_mmHg</th>\n",
              "      <th>Glucose_mg/dL</th>\n",
              "      <th>Dietary_Restrictions</th>\n",
              "      <th>Allergies</th>\n",
              "      <th>Preferred_Cuisine</th>\n",
              "      <th>Weekly_Exercise_Hours</th>\n",
              "      <th>Adherence_to_Diet_Plan</th>\n",
              "      <th>Dietary_Nutrient_Imbalance_Score</th>\n",
              "      <th>Diet_Recommendation</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>P0001</td>\n",
              "      <td>56</td>\n",
              "      <td>Male</td>\n",
              "      <td>58.4</td>\n",
              "      <td>160</td>\n",
              "      <td>22.8</td>\n",
              "      <td>Obesity</td>\n",
              "      <td>Moderate</td>\n",
              "      <td>Moderate</td>\n",
              "      <td>3079</td>\n",
              "      <td>173.3</td>\n",
              "      <td>133</td>\n",
              "      <td>116.3</td>\n",
              "      <td>NaN</td>\n",
              "      <td>Peanuts</td>\n",
              "      <td>Mexican</td>\n",
              "      <td>3.1</td>\n",
              "      <td>96.6</td>\n",
              "      <td>3.1</td>\n",
              "      <td>Balanced</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>P0002</td>\n",
              "      <td>69</td>\n",
              "      <td>Male</td>\n",
              "      <td>101.2</td>\n",
              "      <td>169</td>\n",
              "      <td>35.4</td>\n",
              "      <td>Diabetes</td>\n",
              "      <td>Mild</td>\n",
              "      <td>Moderate</td>\n",
              "      <td>3032</td>\n",
              "      <td>199.2</td>\n",
              "      <td>120</td>\n",
              "      <td>137.1</td>\n",
              "      <td>NaN</td>\n",
              "      <td>Peanuts</td>\n",
              "      <td>Chinese</td>\n",
              "      <td>4.5</td>\n",
              "      <td>63.2</td>\n",
              "      <td>0.6</td>\n",
              "      <td>Low_Carb</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>P0003</td>\n",
              "      <td>46</td>\n",
              "      <td>Female</td>\n",
              "      <td>63.5</td>\n",
              "      <td>173</td>\n",
              "      <td>21.2</td>\n",
              "      <td>Hypertension</td>\n",
              "      <td>Mild</td>\n",
              "      <td>Sedentary</td>\n",
              "      <td>1737</td>\n",
              "      <td>181.0</td>\n",
              "      <td>121</td>\n",
              "      <td>109.6</td>\n",
              "      <td>NaN</td>\n",
              "      <td>Peanuts</td>\n",
              "      <td>Chinese</td>\n",
              "      <td>3.8</td>\n",
              "      <td>57.5</td>\n",
              "      <td>4.6</td>\n",
              "      <td>Low_Sodium</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>P0004</td>\n",
              "      <td>32</td>\n",
              "      <td>Male</td>\n",
              "      <td>58.1</td>\n",
              "      <td>164</td>\n",
              "      <td>21.6</td>\n",
              "      <td>NaN</td>\n",
              "      <td>Mild</td>\n",
              "      <td>Moderate</td>\n",
              "      <td>2657</td>\n",
              "      <td>168.2</td>\n",
              "      <td>144</td>\n",
              "      <td>159.4</td>\n",
              "      <td>NaN</td>\n",
              "      <td>NaN</td>\n",
              "      <td>Mexican</td>\n",
              "      <td>4.3</td>\n",
              "      <td>54.5</td>\n",
              "      <td>0.4</td>\n",
              "      <td>Balanced</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>P0005</td>\n",
              "      <td>60</td>\n",
              "      <td>Male</td>\n",
              "      <td>79.5</td>\n",
              "      <td>197</td>\n",
              "      <td>20.5</td>\n",
              "      <td>Diabetes</td>\n",
              "      <td>Moderate</td>\n",
              "      <td>Sedentary</td>\n",
              "      <td>3496</td>\n",
              "      <td>200.4</td>\n",
              "      <td>172</td>\n",
              "      <td>182.3</td>\n",
              "      <td>Low_Sugar</td>\n",
              "      <td>NaN</td>\n",
              "      <td>Italian</td>\n",
              "      <td>9.8</td>\n",
              "      <td>78.2</td>\n",
              "      <td>4.7</td>\n",
              "      <td>Low_Carb</td>\n",
              "    </tr>\n",
